#!/usr/bin/env bash

# startup a "default" session if non currently exists
# tmux has-session -t _default || tmux new-session -s _default -d

# present menu for user to choose which workspace to open

NAME=$(hostname)
options=$(echo -e "New session"; tmux has-session -t "${NAME}" 2>/dev/null || echo -e "Create ${NAME}"; echo $(tmux list-sessions -F "#S" 2>/dev/null) | xargs -n 1)

choice=$(printf "%s" "$options" | fzf)

case "$choice" in
		"New session")
			read -rp "Enter new session name: " NAME
			tmux has-session -t "${NAME}" 2>/dev/null || tmux new-session -d -s "${NAME}"
			tmux switch-client -t "${NAME}" 2>/dev/null || tmux attach-session -t "${NAME}"
			;;
		"Create ${NAME}")
			tmux has-session -t "${NAME}" 2>/dev/null || tmux new-session -d -s "${NAME}" -c "$WORKSPACE"
			tmux switch-client -t "${NAME}" 2>/dev/null || tmux attach-session -t "${NAME}"
			;;
		*)
			tmux switch-client -t "$choice" 2>/dev/null || tmux attach-session -t "$choice"
			;;
	esac
