#!/usr/bin/env bash

# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0
# startup a "default" session if non currently exists
# tmux has-session -t _default || tmux new-session -s _default -d

# present menu for user to choose which workspace to open
NAME="Pluto"
PS3="Please choose your session: "
# shellcheck disable=SC2207
cnt=$(tmux list-sessions -F "#S" 2>/dev/null| grep -e "^${NAME}$" | wc -l)
options=($(tmux list-sessions -F "#S" 2>/dev/null) "New Session")
if [ "$cnt" -eq "0" ]; then
	options=("Create ${NAME}" "$options")
fi
echo "Available sessions"
echo "------------------"
echo " "
select opt in "${options[@]}"
do
	case $opt in
		"New Session")
			read -rp "Enter new session name: " SESSION_NAME
			tmux new -s "$SESSION_NAME"
			break
			;;
		"zsh")
			zsh --login
			break;;
		"Create ${NAME}")
			tmux new -s "${NAME}" -c "cd /c/workspace"
			break
			;;
		*)
			tmux attach-session -t "$opt"
			break
			;;
	esac
done
