#!/usr/bin/env bash

projects=/c/workspace
candidates=$(find $projects -mindepth 1 -maxdepth 1 -type d -not -path '*/.*')


if [[ $# -eq 1 ]]; then
    selected=$1
    cand=$(printf "%s\n" "$candidates" | grep $1)
    c=$(printf "%s\n" "$cand" | wc -l)
    if [ $c -eq 1 ]; then
        selected=$cand
    else
        selected=$(printf "%s\n" "$cand" | fzf)
    fi
else
    selected=$(printf "%s\n" "$candidates" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name || tmux attach-session -t $selected_name
